# Use Ubuntu as the base image
FROM ubuntu:latest

# Install necessary packages
RUN apt update && apt install -y build-essential net-tools vim

# Set work directory
WORKDIR /workspace

# Default command
CMD ["/bin/bash"]
